#!/usr/bin/env python3
"""Write the main online/offline performance table as CSV and terminal text."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

from reporting_common import (
    PAPER_ENVIRONMENTS,
    PUBLISHED_OFFLINE,
    RANGES,
    ResultsError,
    load_reward_runs,
    main_reward_specs,
    print_rows,
    summarize_reward_methods,
    write_csv,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--range", choices=("general", "low", "all"), default="all")
    parser.add_argument("--offline-summary", type=Path, help="Optional CSV generated by table_offline_bc_ileed.py")
    return parser.parse_args()


def offline_rows(path: Path | None, range_keys) -> list[dict]:
    if path:
        with path.open(newline="", encoding="utf-8") as handle:
            source = list(csv.DictReader(handle))
        return [
            {
                "range": row["range"],
                "environment": row["environment"],
                "method": row["method"],
                "seed_count": row.get("net_seed_count", ""),
                "mean_last_five": row["mean"],
                "std_last_five": row["std"],
                "seed_values": "",
            }
            for row in source
            if row.get("metric") == "best_last5_mean_eval" and row["range"] in range_keys
        ]
    return [
        {
            "range": range_key,
            "environment": environment,
            "method": method,
            "seed_count": "published",
            "mean_last_five": mean,
            "std_last_five": std,
            "seed_values": "",
        }
        for (range_key, method, environment), (mean, std) in PUBLISHED_OFFLINE.items()
        if range_key in range_keys
    ]


def main() -> int:
    args = parse_args()
    range_keys = tuple(RANGES) if args.range == "all" else (args.range,)
    rows = []
    for range_key in range_keys:
        config = RANGES[range_key]
        methods = [
            (label, load_reward_runs(args.results_root, spec))
            for label, _, spec in main_reward_specs(config)
        ]
        rows.extend(summarize_reward_methods(methods, PAPER_ENVIRONMENTS, range_key))
    rows.extend(offline_rows(args.offline_summary, range_keys))
    rows.sort(key=lambda row: (row["range"], row["environment"], row["method"]))
    print_rows(rows)
    write_csv(rows, args.output_dir / "table_main_performance.csv")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ResultsError as exc:
        raise SystemExit(f"error: {exc}") from exc
